### ISSUE TITLE
discopythonが動作しない

### ISSUE THREAD

**Issue by gx1285** [LasteSoft/discopython#1]
### Summary

discopythonが使えない。

### Reproduction Steps

```py
import discord
from discord.ext import commands
import os
bot = commands.Bot(command_prefix='>')

@bot.command()
async def ping(ctx):
    await ctx.send('pong')

bot.run(os.getenv('token'))

```

### Minimal Reproducible Code

```python
import discord
from discord.ext import commands
import os
bot = commands.Bot(command_prefix='>')

@bot.command()
async def ping(ctx):
    await ctx.send('pong')

bot.run(os.getenv('token'))
```

### Expected Results

botが起動

### Actual Results

```py
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import discord
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/__init__.py", line 25, in <module>
    from .client import Client
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 53, in <module>
    from .webhook import Webhook
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/webhook/__init__.py", line 12, in <module>
    from .async_ import *
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/webhook/async_.py", line 46, in <module>
    from ..channel import PartialMessageable
ImportError: cannot import name 'PartialMessageable' from 'discord.channel' (/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/channel.py)
```

### Intents

None

### System Information

```py
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/__init__.py", line 25, in <module>
    from .client import Client
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 53, in <module>
    from .webhook import Webhook
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/webhook/__init__.py", line 12, in <module>
    from .async_ import *
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/webhook/async_.py", line 46, in <module>
    from ..channel import PartialMessageable
ImportError: cannot import name 'PartialMessageable' from 'discord.channel' (/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/channel.py)
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [x] I have removed my token from display, if visible.

### Additional Context

https://github.com/LasteSoft/discopython/blob/master/discord/webhook/async_.py

**Comment by gx1285** [comment]
discopythonのサポートは終了しました。
